//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public string MaNV { get; set; }
        public Nullable<int> LuongCung { get; set; }
        public Nullable<int> NgayNghi { get; set; }
        public Nullable<int> Phucap { get; set; }
        public Nullable<int> TongLuong { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
