//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.DANGNHAPs = new HashSet<DANGNHAP>();
            this.NHANVIEN1 = new HashSet<NHANVIEN>();
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public string MaNV { get; set; }
        public string MaHD { get; set; }
        public string HotenNV { get; set; }
        public Nullable<System.DateTime> NgSinh { get; set; }
        public string Dchi { get; set; }
        public string Phai { get; set; }
        public string MaNQL { get; set; }
        public string Phong { get; set; }
        public string Hinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGNHAP> DANGNHAPs { get; set; }
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual LUONG LUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIEN1 { get; set; }
        public virtual NHANVIEN NHANVIEN2 { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
        public virtual THANNHAN THANNHAN { get; set; }
    }
}
