//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANNHAN
    {
        public string MaNV { get; set; }
        public string HotenTN { get; set; }
        public string VaiTro { get; set; }
        public string SDT { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
